package dao

const (
	USER_STATUS_APPLYING = "0"
	USER_STATUS_NORMAL   = "1"
	USER_STATUS_REJECT   = "2"
)

const (
	REPORT_STATUS_APPLYING = "0"
	REPORT_STATUS_NORMAL   = "1"
	REPORT_STATUS_REJECT   = "2"
)

const (
	PENALTY_STATUS_WAITPAY = "0"
	REPORT_STATUS_PAID     = "1"
)

const (
	AUCTION_STATUS_WAITOPEN     = "0"
	AUCTION_STATUS_WAIT_DECRYPT = "1"
	AUCTION_STATUS_FINISH       = "2"
)

const (
	BIDDING_STATUS_WAIT_START    = "0"
	BIDDING_STATUS_AWAIT_DECRYPT = "1"
	BIDDING_STATUS_AWAIT_OPEN    = "2"
	BIDDING_STATUS_AWAIT_PAYMENT = "3"
	BIDDING_STATUS_AWAIT_REFUND  = "4"
	BIDDING_STATUS_FINISHED      = "5"
)
